# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4QC72zLiViaUe6LsMuWFTRbACudp3Mw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""loading dataset"""

df = pd.read_csv("Titanic-Dataset.csv")

print(df.head())

print(df.tail())

print(df.info())

print(df.shape)

print(df.columns)

print(df.describe())

"""Missing values"""

print(df.isnull().sum())

median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

print(df.isnull().sum())

mode_embarked = df["Embarked"].mode()[0]
df["Embarked"] = df["Embarked"].fillna(mode_embarked)

print(df.isnull().sum())

df["Cabin"] = df["Cabin"].fillna("Unknown")

print(df.isnull().sum())

"""duplicate rows"""

duplicates = df.duplicated().sum()
print("Duplicate Rows:", duplicates)

"""outliers"""

Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df = df[(df["Fare"] >= lower_limit) & (df["Fare"] <= upper_limit)]

"""visualization"""

plt.figure(figsize=(6,4))
sns.countplot(x="Survived", data=df)
plt.title("Survival Count")
plt.xlabel("Survived")
plt.ylabel("Number of Passengers")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["Age"], bins=20, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x="Sex", data=df)
plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

"""correlation heatmap"""

plt.figure(figsize=(8,6))
numeric_data = df.select_dtypes(include=["number"])
sns.heatmap(numeric_data.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()